---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install basic packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - htop
      - git
      - vim-nox
