---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install basic packages
    apt:
      name:
        - htop
        - git
        - vim-nox
      state: present
